#include <iostream>
#include <string>
#include <vector>
#include <map>

#include "../Compiler/action_parser.h"

typedef unsigned char byte;

std::map<registries_def, byte> registers_set = {
	{AH,  0x01},
	{AL,  0x02},
	{AX,  0x03},
	{BH,  0x04},
	{BL,  0x05},
	{BX,  0x06},
	{CH,  0x07},
	{CL,  0x08},
	{CX,  0x09},
	{DH,  0x0A},
	{DL,  0x0B},
	{DX,  0x0C},
	{EAX, 0x0D},
	{EBX, 0x0E},
	{ECX, 0x0F},
	{EDX, 0x10},
	{RAX, 0x11},
	{RBX, 0x12},
	{RCX, 0x13},
	{RDX, 0x14}
};
std::map<virtual_actions, byte> instructions_set = {
	{virtual_actions::getAX,  0x01},
	{virtual_actions::getBX,  0x02},
	{virtual_actions::getCX,  0x03},
	{virtual_actions::getDX,  0x04},
	{virtual_actions::getEAX, 0x05},
	{virtual_actions::getEBX, 0x06},
	{virtual_actions::getECX, 0x07},
	{virtual_actions::getEDX, 0x08},
	{virtual_actions::getRAX, 0x09},
	{virtual_actions::getRBX, 0x0A},
	{virtual_actions::getRCX, 0x0B},
	{virtual_actions::getRDX, 0x0C},

	{virtual_actions::setAX,  0x0D},
	{virtual_actions::setBX,  0x0E},
	{virtual_actions::setCX,  0x0F},
	{virtual_actions::setDX,  0x10},
	{virtual_actions::setEAX, 0x11},
	{virtual_actions::setEBX, 0x12},
	{virtual_actions::setECX, 0x13},
	{virtual_actions::setEDX, 0x14},
	{virtual_actions::setRAX, 0x15},
	{virtual_actions::setRBX, 0x16},
	{virtual_actions::setRCX, 0x17},
	{virtual_actions::setRDX, 0x18},

	{virtual_actions::setSR,  0x19},
	{virtual_actions::getSR,  0x1A},

	{virtual_actions::movAX,  0x1B},
	{virtual_actions::movBX,  0x1C},
	{virtual_actions::movCX,  0x1D},
	{virtual_actions::movDX,  0x1E},
	{virtual_actions::movEAX, 0x1F},
	{virtual_actions::movEBX, 0x20},
	{virtual_actions::movECX, 0x21},
	{virtual_actions::movEDX, 0x22},
	{virtual_actions::movRAX, 0x23},
	{virtual_actions::movRBX, 0x24},
	{virtual_actions::movRCX, 0x25},
	{virtual_actions::movRDX, 0x26},

	{virtual_actions::inc,	  0x27},
	{virtual_actions::dec,	  0x28},

	{virtual_actions::mulAX,  0x29},
	{virtual_actions::mulBX,  0x2A},
	{virtual_actions::mulCX,  0x2B},
	{virtual_actions::mulDX,  0x2C},
	{virtual_actions::mulEAX, 0x2D},
	{virtual_actions::mulEBX, 0x2E},
	{virtual_actions::mulECX, 0x2F},
	{virtual_actions::mulEDX, 0x30},
	{virtual_actions::mulRAX, 0x31},
	{virtual_actions::mulRBX, 0x32},
	{virtual_actions::mulRCX, 0x33},
	{virtual_actions::mulRDX, 0x34},
	
	{virtual_actions::divAX,  0x35},
	{virtual_actions::divBX,  0x36},
	{virtual_actions::divCX,  0x37},
	{virtual_actions::divDX,  0x38},
	{virtual_actions::divEAX, 0x39},
	{virtual_actions::divEBX, 0x3A},
	{virtual_actions::divECX, 0x3B},
	{virtual_actions::divEDX, 0x3C},
	{virtual_actions::divRAX, 0x3D},
	{virtual_actions::divRBX, 0x3E},
	{virtual_actions::divRCX, 0x3F},
	{virtual_actions::divRDX, 0x40},

	{virtual_actions::addAX,  0x41},
	{virtual_actions::addBX,  0x42},
	{virtual_actions::addCX,  0x43},
	{virtual_actions::addDX,  0x44},
	{virtual_actions::addEAX, 0x45},
	{virtual_actions::addEBX, 0x46},
	{virtual_actions::addECX, 0x47},
	{virtual_actions::addEDX, 0x48},
	{virtual_actions::addRAX, 0x49},
	{virtual_actions::addRBX, 0x4A},
	{virtual_actions::addRCX, 0x4B},
	{virtual_actions::addRDX, 0x4C},

	{virtual_actions::subAX,  0x4D},
	{virtual_actions::subBX,  0x4E},
	{virtual_actions::subCX,  0x4F},
	{virtual_actions::subDX,  0x50},
	{virtual_actions::subEAX, 0x51},
	{virtual_actions::subEBX, 0x52},
	{virtual_actions::subECX, 0x53},
	{virtual_actions::subEDX, 0x54},
	{virtual_actions::subRAX, 0x55},
	{virtual_actions::subRBX, 0x56},
	{virtual_actions::subRCX, 0x57},
	{virtual_actions::subRDX, 0x58},

	{virtual_actions::toString,		0x59},
	{virtual_actions::mergeString,	0x5A},
	{virtual_actions::substring,	0x5B},
	{virtual_actions::_strlen,		0x5C},
	{virtual_actions::rdstdin,		0x5D},
	{virtual_actions::print,		0x5E},
	{virtual_actions::println,		0x5F},
	{virtual_actions::printEOL,		0x60},

	{virtual_actions::castreg,		0x61},
	{virtual_actions::recast,		0x62},
	{virtual_actions::fromString,	0x63},

	{virtual_actions::push, 0x64},
	{virtual_actions::pop,  0x65},

	{virtual_actions::pushSR, 0x66},
	{virtual_actions::popSR,  0x67},

	{virtual_actions::declArray,  0x68},
	{virtual_actions::setAt,	  0x69},
	{virtual_actions::getAt,	  0x7A},
	{virtual_actions::getDynSize, 0x7B},

	{virtual_actions::dyndecl, 0x7C},
	{virtual_actions::dynset,  0x7D},
	{virtual_actions::dynget,  0x7E},

	{virtual_actions::_struct,			0x7F},
	{virtual_actions::_struct_declprop, 0x80},
	{virtual_actions::_struct_select,   0x81},
	{virtual_actions::_struct_get,		0x82},
	{virtual_actions::_struct_set,      0x83},

	{virtual_actions::_not, 0x84},
	{virtual_actions::_and, 0x85},
	{virtual_actions::_or,  0x86},
	{virtual_actions::_xor, 0x87},
	{virtual_actions::_shl, 0x88},
	{virtual_actions::_shr, 0x89},
	
	{virtual_actions::_log,   0x8A},
	{virtual_actions::_log2,  0x8B},
	{virtual_actions::_log10, 0x8C},
	{virtual_actions::_pow,   0x8D},

	{virtual_actions::ijmp,   0x8E},
	{virtual_actions::jmp,    0x8F},
	{virtual_actions::cmp,    0x90},
	{virtual_actions::je,     0x91},
	{virtual_actions::jne,    0x92},
	{virtual_actions::jl,     0x93},
	{virtual_actions::jg,     0x94},
	{virtual_actions::jle,    0x95},
	{virtual_actions::jge,    0x96},
	{virtual_actions::cmpstr, 0x97},
	
	{virtual_actions::gca, 0x98},
	{virtual_actions::hlt, 0x99},

	{virtual_actions::call,   0x9A},
	{virtual_actions::lcall,  0x9B},
	{virtual_actions::ret,    0x9C},
	{virtual_actions::svcall, 0x9D},
	{virtual_actions::rscall, 0x9E}
};